<template><div><h1 id="set" tabindex="-1"><a class="header-anchor" href="#set"><span>Set</span></a></h1>
<p>Set继承于Collection接口，是一个<strong>不允许出现重复元素，并且无序的集合</strong>，主要有<strong>HashSet</strong>和<strong>TreeSet</strong>两大实现类。</p>
<blockquote>
<p>在判断重复元素的时候，Set集合会调用hashCode()和equal()方法来实现。</p>
</blockquote>
<p><strong>set集合框架：</strong></p>
<p><img src="@source/../resource/images/image-20200720111941046.png" alt="image-20200720111941046"></p>
<h2 id="hashset" tabindex="-1"><a class="header-anchor" href="#hashset"><span>HashSet</span></a></h2>
<p>HashSet是哈希表结构，主要利用HashMap的key来存储元素，计算插入元素的hashCode来获取元素在集合中的位置；</p>
<blockquote>
<p>HashSet实现Set接口，底层由HashMap来实现，为哈希表结构，<strong>新增元素相当于HashMap的key，value默认为一个固定的Object</strong>。</p>
<p>当有元素插入的时候，会计算元素的hashCode值，将元素插入到哈希表对应的位置中来；</p>
<p>它继承于AbstractSet，实现了Set, Cloneable, Serializable接口。</p>
<p>(1)HashSet继承AbstractSet类，获得了Set接口大部分的实现，减少了实现此接口所需的工作，实际上是又继承了AbstractCollection类；</p>
<p>(2)HashSet实现了Set接口，获取Set接口的方法，可以自定义具体实现，也可以继承AbstractSet类中的实现；</p>
<p>(3)HashSet实现Cloneable，得到了clone()方法，可以实现克隆功能；</p>
<p>(4)HashSet实现Serializable，表示可以被序列化，通过序列化去传输，典型的应用就是hessian协议。</p>
</blockquote>
<p>特点：</p>
<ul>
<li>不允许出现重复元素</li>
<li>允许插入null值</li>
<li>元素无序（添加顺序和遍历顺序不一致）</li>
<li>线程不安全，如两个线程同时操作HashSet，必须通过代码实现同步</li>
</ul>
<p><strong>HashSet的基本操作</strong></p>
<p>由于Set集合中并没有角标的概念，所以并没有像List一样提供get（）方法。当获取HashSet中某个元素时，只能通过遍历集合的方式进行equals()比较来实现；</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code class="language-java"><span class="line"><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>        </span>
<span class="line">    <span class="token comment">//创建HashSet集合：        </span></span>
<span class="line">    <span class="token class-name">Set</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> hashSet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HashSet</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"HashSet初始容量大小："</span><span class="token operator">+</span>hashSet<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token comment">//元素添加：        </span></span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"my"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"is"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"jiaboyan"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">","</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"hello"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"world"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"!"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"HashSet容量大小："</span><span class="token operator">+</span>hashSet<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token comment">//迭代器遍历：        </span></span>
<span class="line">    <span class="token class-name">Iterator</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> iterator <span class="token operator">=</span> hashSet<span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token keyword">while</span> <span class="token punctuation">(</span>iterator<span class="token punctuation">.</span><span class="token function">hasNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>            </span>
<span class="line">        <span class="token class-name">String</span> str <span class="token operator">=</span> iterator<span class="token punctuation">.</span><span class="token function">next</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>            </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token punctuation">}</span>        </span>
<span class="line">    <span class="token comment">//增强for循环        </span></span>
<span class="line">    <span class="token keyword">for</span><span class="token punctuation">(</span><span class="token class-name">String</span> str<span class="token operator">:</span>hashSet<span class="token punctuation">)</span><span class="token punctuation">{</span>            </span>
<span class="line">        <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token string">"jiaboyan"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>                </span>
<span class="line">            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"你就是我想要的元素:"</span><span class="token operator">+</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>            </span>
<span class="line">        <span class="token punctuation">}</span>            </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>        <span class="token punctuation">}</span>        </span>
<span class="line">    <span class="token comment">//元素删除：       </span></span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span><span class="token string">"jiaboyan"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"HashSet元素大小："</span> <span class="token operator">+</span> hashSet<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    hashSet<span class="token punctuation">.</span><span class="token function">clear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"HashSet元素大小："</span> <span class="token operator">+</span> hashSet<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token comment">//集合判断：        </span></span>
<span class="line">    <span class="token keyword">boolean</span> isEmpty <span class="token operator">=</span> hashSet<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"HashSet是否为空："</span> <span class="token operator">+</span> isEmpty<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token keyword">boolean</span> isContains <span class="token operator">=</span> hashSet<span class="token punctuation">.</span><span class="token function">contains</span><span class="token punctuation">(</span><span class="token string">"hello"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"HashSet是否为空："</span> <span class="token operator">+</span> isContains<span class="token punctuation">)</span><span class="token punctuation">;</span>    </span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="hashset元素添加不允许重复分析" tabindex="-1"><a class="header-anchor" href="#hashset元素添加不允许重复分析"><span>HashSet元素添加不允许重复分析</span></a></h3>
<p>在向HashSet中添加元素时会先判断它的hash值是否相同，相同的话再进行equals(),的判断，若相同则覆盖原有的元素，如不同则直接添加。</p>
<h2 id="treeset" tabindex="-1"><a class="header-anchor" href="#treeset"><span>TreeSet</span></a></h2>
<p>TreeSet是红黑树结构，每一个元素都是树中的一个节点，插入的元素都会进行排序；</p>
<p>与HashSet集合类似，TreeSet也是基于Map来实现，具体实现<strong>TreeMap</strong>(后面讲解)，其底层结构为<strong>红黑树</strong>（特殊的二叉查找树）；</p>
<p>与HashSet不同的是，TreeSet具有排序功能，分为自然排序(123456)和自定义排序两类，默认是自然排序；在程序中，我们可以按照任意顺序将元素插入到集合中，等到遍历时TreeSet会按照一定顺序输出--倒序或者升序；</p>
<blockquote>
<p>它继承AbstractSet，实现NavigableSet, Cloneable, Serializable接口。</p>
<p>（1）与HashSet同理，TreeSet继承AbstractSet类，获得了Set集合基础实现操作；</p>
<p>（2）TreeSet实现NavigableSet接口，而NavigableSet又扩展了SortedSet接口。这两个接口主要定义了搜索元素的能力，例如给定某个元素，查找该集合中比给定元素大于、小于、等于的元素集合，或者比给定元素大于、小于、等于的元素个数；简单地说，实现NavigableSet接口使得TreeSet具备了元素搜索功能；</p>
<p>（3）TreeSet实现Cloneable接口，意味着它也可以被克隆；</p>
<p>（4）TreeSet实现了Serializable接口，可以被序列化，可以使用hessian协议来传输；</p>
</blockquote>
<p><strong>特点：</strong></p>
<ul>
<li>对插入的元素进行排序，是一个有序的集合（主要与HashSet的区别）;</li>
<li>底层使用红黑树结构，而不是哈希表结构；</li>
<li>允许插入Null值；</li>
<li>不允许插入重复元素；</li>
<li>线程不安全；</li>
</ul>
<p><strong>TreeSet的基本操作</strong></p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code class="language-java"><span class="line"><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">TreeSetTest</span> <span class="token punctuation">{</span>    </span>
<span class="line">    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">void</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token class-name">String</span><span class="token punctuation">[</span><span class="token punctuation">]</span> agrs<span class="token punctuation">)</span><span class="token punctuation">{</span>        </span>
<span class="line">        <span class="token class-name">TreeSet</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> treeSet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">TreeSet</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"TreeSet初始化容量大小："</span><span class="token operator">+</span>treeSet<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        <span class="token comment">//元素添加：        </span></span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"my"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"jiaboyan"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"hello"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"world"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"1"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"2"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string">"3"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>       </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"TreeSet容量大小："</span> <span class="token operator">+</span> treeSet<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"TreeSet元素顺序为："</span> <span class="token operator">+</span> treeSet<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">//增加for循环遍历：        </span></span>
<span class="line">        <span class="token keyword">for</span><span class="token punctuation">(</span><span class="token class-name">String</span> str<span class="token operator">:</span>treeSet<span class="token punctuation">)</span><span class="token punctuation">{</span>            </span>
<span class="line">            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"遍历元素："</span><span class="token operator">+</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token punctuation">}</span>       </span>
<span class="line">        <span class="token comment">//迭代器遍历：升序        </span></span>
<span class="line">        <span class="token class-name">Iterator</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> iteratorAesc <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token keyword">while</span><span class="token punctuation">(</span>iteratorAesc<span class="token punctuation">.</span><span class="token function">hasNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>            </span>
<span class="line">            <span class="token class-name">String</span> str <span class="token operator">=</span> iteratorAesc<span class="token punctuation">.</span><span class="token function">next</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>            </span>
<span class="line">            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"遍历元素升序："</span><span class="token operator">+</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token punctuation">}</span>        </span>
<span class="line">        <span class="token comment">//迭代器遍历：降序        </span></span>
<span class="line">        <span class="token class-name">Iterator</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> iteratorDesc <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">descendingIterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token keyword">while</span><span class="token punctuation">(</span>iteratorDesc<span class="token punctuation">.</span><span class="token function">hasNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>            </span>
<span class="line">            <span class="token class-name">String</span> str <span class="token operator">=</span> iteratorDesc<span class="token punctuation">.</span><span class="token function">next</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>            </span>
<span class="line">            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"遍历元素降序："</span><span class="token operator">+</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token punctuation">}</span>       </span>
<span class="line">        <span class="token comment">//元素获取:实现NavigableSet接口        </span></span>
<span class="line">        <span class="token class-name">String</span> firstEle <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">first</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token comment">//获取TreeSet头节点：        </span></span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"TreeSet头节点为："</span> <span class="token operator">+</span> firstEle<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">// 获取指定元素之前的所有元素集合：(不包含指定元素)        </span></span>
<span class="line">        <span class="token class-name">SortedSet</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> headSet <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">headSet</span><span class="token punctuation">(</span><span class="token string">"jiaboyan"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"jiaboyan节点之前的元素为："</span><span class="token operator">+</span>headSet<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">//获取给定元素之间的集合：（包含头，不包含尾）        </span></span>
<span class="line">        <span class="token class-name">SortedSet</span> subSet <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">subSet</span><span class="token punctuation">(</span><span class="token string">"1"</span><span class="token punctuation">,</span><span class="token string">"world"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"1--jiaboan之间节点元素为："</span><span class="token operator">+</span>subSet<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">//集合判断：        </span></span>
<span class="line">        <span class="token keyword">boolean</span> isEmpty <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"TreeSet是否为空："</span><span class="token operator">+</span>isEmpty<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token keyword">boolean</span> isContain <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">contains</span><span class="token punctuation">(</span><span class="token string">"who"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"TreeSet是否包含who元素："</span><span class="token operator">+</span>isContain<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">//元素删除：        </span></span>
<span class="line">        <span class="token keyword">boolean</span> jiaboyanRemove <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span><span class="token string">"jiaboyan"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"jiaboyan元素是否被删除"</span><span class="token operator">+</span>jiaboyanRemove<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">//集合中不存在的元素，删除返回false        </span></span>
<span class="line">        <span class="token keyword">boolean</span> whoRemove <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span><span class="token string">"who"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"who元素是否被删除"</span><span class="token operator">+</span>whoRemove<span class="token punctuation">)</span><span class="token punctuation">;</span>       </span>
<span class="line">        <span class="token comment">//删除并返回第一个元素：如果set集合不存在元素，则返回null        </span></span>
<span class="line">        <span class="token class-name">String</span> pollFirst <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">pollFirst</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"删除的第一个元素："</span><span class="token operator">+</span>pollFirst<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token comment">//删除并返回最后一个元素：如果set集合不存在元素，则返回null        </span></span>
<span class="line">        <span class="token class-name">String</span> pollLast <span class="token operator">=</span> treeSet<span class="token punctuation">.</span><span class="token function">pollLast</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"删除的最后一个元素："</span><span class="token operator">+</span>pollLast<span class="token punctuation">)</span><span class="token punctuation">;</span>        </span>
<span class="line">        treeSet<span class="token punctuation">.</span><span class="token function">clear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//清空集合:    </span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="treeset元素排序" tabindex="-1"><a class="header-anchor" href="#treeset元素排序"><span>TreeSet元素排序</span></a></h3>
<p>TreeSet是一个有序集合，可以对集合元素排序，其中分为<strong>自然排序</strong>和<strong>自定义排序</strong></p>
<blockquote>
<p><strong>自然排序：</strong> 自然排序就是数字0-9，字母a-z。</p>
<p><strong>自定义对象不支持自然排序</strong> ：因为TreeSet会调用<code v-pre>compareTo</code>方法进行排序，自定义类需要实现<code v-pre>Comparable</code>接口并重写<code v-pre>compareTo</code>方法，或者使用<code v-pre>Comparator</code>接口和<code v-pre>compare</code>方法。</p>
</blockquote>
<p>compareTo()、compare()方法：</p>
<ul>
<li>结果返回大于0时，方法前面的值大于方法中的值；</li>
<li>结果返回等于0时，方法前面的值等于方法中的值；</li>
<li>结果返回小于0时，方法前面的值小于方法中的值；</li>
</ul>
</div></template>


